name2 = "levani" 
print(name2.lower())
name3 = " papava "
print(name3)
print(name3.strip())
print(name3.replace(" ", " # "))
name4 = "  avdocatus diaboli  "
print(name4)
print( "d" in name4)
print("d" not in name4)
print(len(name4))
print(name4.upper())
print(name4.lower())
print(name4[7])
print(name4[0:5])
print(name4[3:9:2])
print(name4[-1])
print(name4)
print(name4.strip())
print(len(name4))
print(name4.replace("a", "*"))
print(name3.replace("a","#"))